name: Deploy Develop

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed
    branches:
      - test-sync-repo  # Trigger on pushes to the 'main' branch
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Push to Dev Server
        env:
         DEVELOP_REPOSITORY_ACCESS_KEY: ${{ secrets.DEVELOP_REPOSITORY_ACCESS_KEY }}
        run: |
          git remote add develop https://x-access-token:${DEVELOP_REPOSITORY_ACCESS_KEY}@github.com/DamonKert/NCLLL-Frontend.git
          git push --mirror develop
