name: NCLLL-Frontend

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed
    branches:
      - test-sync-repo  # Trigger on pushes to the 'main' branch
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Push to Dev Server
        run: |
          git remote add git@github.com:DamonKert/NCLLL-Frontend.git
          git push --mirror client1
