name: Deploy Develop

on:
  push:
      branches: [ "main" ]# Trigger on pushes to the 'main' branch
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://x-access-token:${{ secrets.DEVELOP_REPOSITORY_ACCESS_KEY }}@github.com/owner/source-repo.git"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.DEVELOP_REPOSITORY_ACCESS_KEY }}
